# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.runs/synth_1/m3_for_arty_a7_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.cache/wt [current_project]
set_property parent.project_path V:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  v:/vivado/Arm_ipi_repository
  e:/repositories/board_files
  e:/Diplomatikh/vivado-ips
  c:/Users/chist/Desktop/Diplomatikh/vivado-ips/vivado-library-master
} [current_project]
update_ip_catalog
set_property ip_output_repo v:/hardware/m3_for_arty_a7/m3_for_arty_a7/m3_for_arty_a7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem V:/hardware/m3_for_arty_a7/m3_for_arty_a7/bram_a7.hex
read_verilog -library xil_defaultlib {
  V:/hardware/m3_for_arty_a7/block_diagram/tri_io_buf.v
  V:/hardware/m3_for_arty_a7/block_diagram/hdl/m3_for_arty_a7_wrapper.v
}
add_files V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7.bd
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0_1/m3_for_arty_a7_proc_sys_reset_DAPLink_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0_1/m3_for_arty_a7_proc_sys_reset_DAPLink_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0_1/m3_for_arty_a7_proc_sys_reset_DAPLink_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0_1/m3_for_arty_a7_proc_sys_reset_base_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0_1/m3_for_arty_a7_proc_sys_reset_base_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0_1/m3_for_arty_a7_proc_sys_reset_base_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0_1/m3_for_arty_a7_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0_1/m3_for_arty_a7_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0_1/m3_for_arty_a7_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0_1/m3_for_arty_a7_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0_1/m3_for_arty_a7_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0_1/m3_for_arty_a7_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0_1/m3_for_arty_a7_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0_1/m3_for_arty_a7_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0_1/m3_for_arty_a7_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0_1/m3_for_arty_a7_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0_1/m3_for_arty_a7_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0_1/m3_for_arty_a7_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0_1/m3_for_arty_a7_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0_1/m3_for_arty_a7_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0_1/m3_for_arty_a7_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0_1/m3_for_arty_a7_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0_1/m3_for_arty_a7_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0_1/m3_for_arty_a7_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0_1/m3_for_arty_a7_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0_1/m3_for_arty_a7_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1_1/m3_for_arty_a7_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0_1/m3_for_arty_a7_axi_single_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0_1/m3_for_arty_a7_axi_single_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0_1/m3_for_arty_a7_axi_single_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0_1/m3_for_arty_a7_axi_single_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1_1/m3_for_arty_a7_axi_quad_spi_0_1_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1_1/m3_for_arty_a7_axi_quad_spi_0_1.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1_1/m3_for_arty_a7_axi_quad_spi_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1_1/m3_for_arty_a7_axi_quad_spi_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0_1/m3_for_arty_a7_axi_xip_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0_1/m3_for_arty_a7_axi_xip_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0_1/m3_for_arty_a7_axi_xip_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0_1/m3_for_arty_a7_axi_xip_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1_1/m3_for_arty_a7_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1_1/m3_for_arty_a7_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1_1/m3_for_arty_a7_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0_1/m3_for_arty_a7_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0_1/m3_for_arty_a7_Cortex_M3_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/m3_for_arty_a7_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/m3_for_arty_a7_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_1_0/m3_for_arty_a7_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_1_0/m3_for_arty_a7_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_1_0/m3_for_arty_a7_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_2_0/m3_for_arty_a7_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_2_0/m3_for_arty_a7_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_2_0/m3_for_arty_a7_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0_1/m3_for_arty_a7_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7.xdc
set_property used_in_implementation false [get_files V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top m3_for_arty_a7_wrapper -part xc7s50csga324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef m3_for_arty_a7_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file m3_for_arty_a7_wrapper_utilization_synth.rpt -pb m3_for_arty_a7_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
