#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : m3_for_arty_a7.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Jan 09 17:34:54 +0200 2021
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: m3_for_arty_a7.sh [-help]
# usage: m3_for_arty_a7.sh [-lib_map_path]
# usage: m3_for_arty_a7.sh [-noclean_files]
# usage: m3_for_arty_a7.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'm3_for_arty_a7.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xil_defaultlib util_vector_logic_v2_0_1 xlconstant_v1_1_7 axi_bram_ctrl_v4_1_3 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_23 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_21 fifo_generator_v13_2_5 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 dist_mem_gen_v8_0_13 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 lib_fifo_v1_0_14 axi_quad_spi_v3_2_20 axi_uartlite_v2_0_25 blk_mem_gen_v8_4_4 axi_protocol_converter_v2_1_21 xlconcat_v2_1_3)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "m3_for_arty_a7.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "D:/RandomShit/Xilinx/VIVADO/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/RandomShit/Xilinx/VIVADO/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/RandomShit/Xilinx/VIVADO/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/RandomShit/Xilinx/VIVADO/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0_1/sim/m3_for_arty_a7_proc_sys_reset_DAPLink_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0_1/sim/m3_for_arty_a7_proc_sys_reset_base_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_interconnect_aresetn_0_1/sim/m3_for_arty_a7_i_interconnect_aresetn_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_peripheral_aresetn1_0_1/sim/m3_for_arty_a7_i_peripheral_aresetn1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_sysresetn_or_0_1/sim/m3_for_arty_a7_i_sysresetn_or_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_inv_dbgresetn_0_1/sim/m3_for_arty_a7_i_inv_dbgresetn_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_i_inv_sysresetn1_0_1/sim/m3_for_arty_a7_i_inv_sysresetn1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0_1/m3_for_arty_a7_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0_1/m3_for_arty_a7_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconstant_1_0_1/sim/m3_for_arty_a7_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_1_3 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/db86/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0_1/sim/m3_for_arty_a7_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0_1/sim/m3_for_arty_a7_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0_1/sim/m3_for_arty_a7_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xbar_0_1/sim/m3_for_arty_a7_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_20 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/1735/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0_1/sim/m3_for_arty_a7_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_25 $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ipshared/43b7/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0_1/sim/m3_for_arty_a7_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0_1/sim/m3_for_arty_a7_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xbar_1_1/sim/m3_for_arty_a7_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0_1/sim/m3_for_arty_a7_axi_single_spi_0_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1_1/sim/m3_for_arty_a7_axi_quad_spi_0_1.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0_1/sim/m3_for_arty_a7_axi_xip_quad_spi_0_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1_1/sim/m3_for_arty_a7_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/8dfa/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0_1/sim/m3_for_arty_a7_axi_protocol_convert_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/5fe9/DAPLink_to_Arty_shield.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0_1/sim/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_tri_io_buf_0_0_1/sim/m3_for_arty_a7_tri_io_buf_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_0_0_1/sim/m3_for_arty_a7_xlconcat_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconcat_1_0_1/sim/m3_for_arty_a7_xlconcat_1_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xlconstant_1_1_1/sim/m3_for_arty_a7_xlconstant_1_1.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_dap_ahb_ap.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_wic.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_nvic.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_dwt.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/AhbToAxi.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_mpu.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_bus_matrix.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/models.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cmsdk.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_tpiu.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/dapswjdp.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_fpb.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_dpu.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_itm.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cm3_etm.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cortexm3.v" \
    "$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl/cortexm3_integration.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0_1/sim/m3_for_arty_a7_Cortex_M3_0_0.v" \
    "$ref_dir/../../../../../block_diagram/sim/m3_for_arty_a7.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_PmodESP32_0_0/ipshared/0a6f/src/pmod_concat.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_PmodESP32_0_0/src/PmodESP32_pmod_bridge_0_0/sim/PmodESP32_pmod_bridge_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_PmodESP32_0_0/src/PmodESP32_axi_uartlite_0_0/sim/PmodESP32_axi_uartlite_0_0.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_PmodESP32_0_0/src/PmodESP32_axi_gpio_0_0/sim/PmodESP32_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ipshared/ec56/src/PmodESP32.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_PmodESP32_0_0/sim/m3_for_arty_a7_PmodESP32_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_ipif_pkg.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_family_support.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_family.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_soft_reset.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_pselect_f.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_address_decoder.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_slave_attachment.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/interrupt_control_v2_01_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_interrupt_control.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/m3_for_arty_a7_xadc_wiz_0_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/m3_for_arty_a7_xadc_wiz_0_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/m3_for_arty_a7_xadc_wiz_0_0_axi_xadc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../block_diagram/ipshared/8b3d" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../block_diagram/ipshared/ea75/rtl" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_xadc_wiz_0_0/m3_for_arty_a7_xadc_wiz_0_0.v" \
    "$ref_dir/../../../../../block_diagram/ip/m3_for_arty_a7_auto_pc_0_1/sim/m3_for_arty_a7_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.m3_for_arty_a7 xil_defaultlib.glbl -o m3_for_arty_a7_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./m3_for_arty_a7_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./m3_for_arty_a7.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key m3_for_arty_a7_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc m3_for_arty_a7_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./m3_for_arty_a7.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: m3_for_arty_a7.sh [-help]\n\
Usage: m3_for_arty_a7.sh [-lib_map_path]\n\
Usage: m3_for_arty_a7.sh [-reset_run]\n\
Usage: m3_for_arty_a7.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
